### ISSUE TITLE
"Error: Cannot find module './node_modules/platform'

### ISSUE THREAD

**Issue by ThunderTwonkDEV** [lucasveneno/trafficbot#1]
You're missing the platform module under node_modules. The folder just isn't there. I just cloned it in my repo for now.

**Comment by giacDaddy** [comment]
Now that I've gotten past that I've gotten another error stating that I'm missing the common module. Which was required by the debug node module. I'm assuming either the how-to needs to be updated or it's just missing as well. Idk.

**Comment by lucasveneno** [comment]
Thanks for the feedback, you can run the script without the debug mode, but I'm gonna add the module to the node folder and update the script asap


________________________________

**Comment by ThunderTwonkDEV** [comment]
Oh nice I’ll try to run it without the debug mode. Thanks!

**Comment by xslyl** [comment]
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/root/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

I have tried to update NPM or nodejs multiple times and I get this error

**Comment by lucasveneno** [comment]
The modules was added

if you guys need a new module install with node npm

https://www.npmjs.com/package/platform
`$ npm i platform`

https://www.npmjs.com/package/debug
`npm i debug`
