### ISSUE TITLE
module.js:549     throw err;

### ISSUE THREAD

**Issue by xslyl** [lucasveneno/trafficbot#3]
module.js:549
    throw err;
    ^

Error: Cannot find module '/home/siluo/index.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by lucasveneno** [comment]
please try again I update and added some modules

**Comment by xslyl** [comment]
Thanks for the reply, i'm trying

**Comment by xslyl** [comment]
root@siluo:/home/siluo# xvfb-run --auto-servernum --server-num=1 --server-args="-screen 0 1024x768x24" node --harmony index.js --url https://iphub.info/ --proxy 127.0.0.1 --port 8080 --user lucas --pass veneno --windows 1 --time 2
module.js:549
    throw err;
    ^

Error: Cannot find module '/home/siluo/index.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3


The fault still exists

**Comment by lucasveneno** [comment]
Please enter in traffic bot main folder and run without the "proxy vars", it looks like Node is not finding the 'index.js' file

`xvfb-run --auto-servernum --server-num=1 --server-args="-screen 0 1024x768x24" node --harmony index.js --url https://iphub.info/ --windows 1 --time 2`

**Comment by xslyl** [comment]
root@siluo:/home/siluo# xvfb-run --auto-servernum --server-num=1 --server-args="-screen 0 1024x768x24" node --harmony index.js --url https://iphub.info/ --windows 1 --time 2
module.js:549
    throw err;
    ^

Error: Cannot find module '/home/siluo/index.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by lucasveneno** [comment]
Using npm install installs the module into the current directory only (in a subdirectory called node_modules). Is index.js located under '/home/siluo/'? If not and you want to use the module from any directory, you need to install it globally using npm install -g.

I usually install most packages locally so that they get checked in along with my project code.

**Comment by xslyl** [comment]
root@bot-2:~# xvfb-run --auto-servernum --server-num=1 --server-args="-screen 0 1024x768x24" node --harmony index.js --url https://iphub.info/ --windows 1 --time 2
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
root@bot-2:~#

**Comment by xslyl** [comment]
> root@bot-2:~# xvfb-run --auto-servernum --server-num=1 --server-args="-screen 0 1024x768x24" node --harmony index.js --url https://iphub.info/ --windows 1 --time 2
> internal/modules/cjs/loader.js:638
> throw err;
> ^
> 
> Error: Cannot find module '/root/index.js'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
> at Function.Module._load (internal/modules/cjs/loader.js:562:25)
> at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
> at startup (internal/bootstrap/node.js:283:19)
> at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
> root@bot-2:~#
> 
> root@bot-2:~# npm install -g
> npm ERR! code ENOLOCAL
> npm ERR! Could not install from "" as it does not contain a package.json file.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /root/.npm/_logs/2020-05-01T10_16_33_668Z-debug.log
> root@bot-2:~# sudo npm install -g
> npm ERR! code ENOLOCAL
> npm ERR! Could not install from "" as it does not contain a package.json file.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /root/.npm/_logs/2020-05-01T10_16_44_863Z-debug.log

.
root@bot-2:~# xvfb-run --auto-servernum --server-num=1 --server-args="-screen 0 1024x768x24" node --harmony index.js --url https://iphub.info/ --windows 1 --time 2
module.js:549
    throw err;
    ^

Error: Cannot find module '/root/index.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
